### PR TITLE
add githubpacthe

### PR DESCRIPTION
**Pull request by misteuk**
this hacks github inlcude fragement so it work s in non Chrome®™ browsers

theyare using ShadowRoot which ive also added to stopthe errors

removed hotfix

### CODE REVIEW

**Comment by SeaHOH** [comment]
It works well.

**Comment by SeaHOH** [comment]
Add getRootNode polyfill, and filter styles of input.
```javascript
(function () {
  // https://github.com/foobarhq/get-root-node-polyfill
  if (Node.prototype.getRootNode === undefined) {
      Node.prototype.getRootNode = function (opt) {
        let composed = typeof opt === "object" && Boolean(opt.composed);
        return composed ? getShadowIncludingRoot(this) : getRoot(this);
      }
      function getShadowIncludingRoot(node) {
        let root = getRoot(node);
        if (isShadowRoot(root))
          return getShadowIncludingRoot(root.host);
        return root;
      }
      function getRoot(node) {
        if (node.parentNode != null)
          return getRoot(node.parentNode);
        return node;
      }
      function isShadowRoot(node) {
        return node.nodeName === "#document-fragment" && node.constructor.name === "ShadowRoot";
      }
  }
  if (window.ShadowRoot === undefined) {
    window.ShadowRoot = class ShadowRoot extends DocumentFragment {
      set innerHTML (html) {
        super.innerHTML = html;
        let css = /<style>([\s\S]+?)<\/style>/.exec(html);
        css = css && css[1];
        if (!css || css.indexOf(":host") < 0) return;
        css = css.replace(/:host\((.+?)\)/g, function (match, selectors) {
              let res = [];
              for (selector of selectors.split(','))
                res.push(this.name + selector);
              return res.join(', ');
            }).replace(/:host-context\((.+?)\)/g, function (match, selectors) {
              let res = [];
              for (selector of selectors.split(','))
                res.push(selector + " > " + this.name);
              return res.join(', ');
            }).replace(/:host/g, this.name);
        if (css && CSS.innerHTML.indexOf(css) < 0)
          CSS.innerHTML += css;
      }
    };
    function attachShadow (init) {
      let sr = new ShadowRoot();
      sr.name = this.ceName;
      Object.defineProperty(sr, "host", {value: this});
      Object.defineProperty(sr, "mode", {value: init.mode});
      Object.defineProperty(sr, "delegatesFocus", {value: Boolean(init.delegatesFocus)});
      if (init.mode === "closed") return null;
      return sr;
    }
    const CSS = document.createElement('style'),
          oldCED = customElements.define;
    document.head.appendChild(CSS);
    customElements.define = function (name, cls, options) {
      if (name === "include-fragment" && cls.prototype.attachShadow === undefined) {
        cls.prototype.ceName = name;
        cls.prototype.attachShadow = attachShadow;
      }
      oldCED.call(customElements, name, cls, options);
    };
  }
}());
```

**Comment by dirkf** [comment]
Yesterday, this appeared to fix the top-right Profile pop-up, ie this:
```html
<details-menu class="dropdown-menu dropdown-menu-sw" style="width: 180px" preload="" role="menu">
      <include-fragment src="/users/nnnnnnn/menu" loading="lazy">
        <p class="text-center mt-3" data-hide-on-error="">
          <svg ...>
          ...
          </svg>
        </p>
        <p ...>
          <svg ...>
          ...
         </svg>
          Sorry, something went wrong.
        </p>
      </include-fragment>
  </details-menu>
```
Today, not.

As before, deleting the `loading` attribute of `<include-fragment...>` causes this whenever the button is clicked:
```
13:21:01.748 TypeError: r.load is not a function details-menu.ts:187:64
	subscribe/< details-menu.ts:187:64
```

Also, the 'Load diffs' misplacement occurs because the styling of the relevant `<include-fragment...>` is wrong: presumably the polyfill didn't accept it.

This style applied using Stylem (etc) or user CSS fixes it for now:
```css
@-moz-document regexp("https?://github\.com/.+/commit/[0-9a-f]+") {
  include-fragment.js-diff-entry-loader {
  	position:  inherit !important;
  }
}
```

**Comment by SeaHOH** [comment]
Thanks a lot.

**Pull request closed without merging**
