### PR TITLE
Async patch HTML

### PR DESCRIPTION
**Pull request by SeaHOH**
https://github.com/JustOff/github-wc-polyfill/commit/cda9476b60ac8e84a477089af1eb2cbfba601928#r43423785

### CODE REVIEW

**Comment by SeaHOH** [comment]
I don't understand, is `try-catch` necessary when call `originalListener` functions?

**Comment by rofl0r** [comment]
it is usually considered helpful to add a description of what a PR does when opening one.

**Comment by SeaHOH** [comment]
Added.

**Comment by JustOff** [comment]
In my tests, this results in an increase in processing time, not a decrease. Can you show an example of the opposite?

**Comment by SeaHOH** [comment]
Not every internet access is fast. The main HTML code usually 100+ kiB size, if it cost 1 to 2 seconds to received all bytes, that lead to delay the same time for loading all needed resources, e.g. script, css, image etc.

**Comment by JustOff** [comment]
Sorry, but that's not what I was asking. Try counting the time between the start of onStartRequest and the end of onStopRequest before and after applying your patch. It seems to me that on large pages it increased and almost did not change on small ones. So what's the profit?

**Comment by SeaHOH** [comment]
This patch is increased a little loading time when via fast connection, but decrease much more time when via slow connection.

**Comment by JustOff** [comment]
Sorry, but it's not at all obvious. There must be a way to test and measure the difference.

**Comment by SeaHOH** [comment]
Maybe you can test it via a proxy who can limit the connections' speed.

**Comment by SeaHOH** [comment]
Do you used [Charles](https://www.charlesproxy.com/), this tool can simulate a lowspeed connection.

**Comment by JustOff** [comment]
Ok, I'll try to play with Fiddler.

**Comment by SeaHOH** [comment]
Hi, did you completed the test yet?

**Comment by JustOff** [comment]
I've been a bit short of time recently and this issue isn't a top priority. I'll let you know as soon as I do.

**Comment by SeaHOH** [comment]
Sorry, I'm not good at English. Please feel free.

**Pull request closed without merging**
